include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - lib/**/*.g.dart

  errors:
    unused_import: warning
    invalid_annotation_target: ignore
    always_specify_types: ignore

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    prefer_collection_literals: true
    avoid_returning_null: true
    always_specify_types: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    unnecessary_this: true
    avoid_unnecessary_containers: true